version: 0.2

phases:
  install:
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Angular code
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`